### ISSUE TITLE
Investigate flaky test failure

### ISSUE THREAD

**Issue by joffrey-bion** [joffrey-bion/krossbow#205]
Failure during `Jdk11WebSocketClientAutobahnTest`, possible race?

```
Unexpected exception during test case 1.2.3: Output closed

Caused by: java.io.IOException: Output closed
at jdk.internal.net.http.websocket.MessageEncoder.encodeBinary(MessageEncoder.java:233)	
at jdk.internal.net.http.websocket.TransportImpl$SendTask$1.onBinary(TransportImpl.java:380)	
at jdk.internal.net.http.websocket.TransportImpl$SendTask$1.onBinary(TransportImpl.java:361)	
at jdk.internal.net.http.websocket.MessageQueue.peek(MessageQueue.java:240)	
at jdk.internal.net.http.websocket.TransportImpl$SendTask.run(TransportImpl.java:549)	
at jdk.internal.net.http.common.SequentialScheduler$CompleteRestartableTask.run(SequentialScheduler.java:149)	
at jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:230)	
at jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:303)	
at jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:256)	
at jdk.internal.net.http.websocket.TransportImpl.sendBinary(TransportImpl.java:174)	
at jdk.internal.net.http.websocket.WebSocketImpl.sendBinary(WebSocketImpl.java:216)	
at org.hildan.krossbow.websocket.jdk.Jdk11WebSocketConnection.sendBinary(Jdk11WebSocketClient.kt:110)	
at org.hildan.krossbow.websocket.test.autobahn.AutobahnClientTestSuiteKt.echoFrame(AutobahnClientTestSuite.kt:274)
```

https://scans.gradle.com/s/nabdwx5elbl4w/tests/:autobahn-tests:jvmOkhttpTest/org.hildan.krossbow.websocket.test.autobahn.Jdk11WebSocketClientAutobahnTest/autobahn_1_2_3_echo_binary_payload?expanded-stacktrace=WyIwLTEtMi0zIl0&top-execution=1

**Comment by joffrey-bion** [comment]
`org.gradle.parallel=true` means that all tasks can run in parallel. The tests within a task are constrained by `maxParallelForks=1`, but there are many test tasks in `autobahn-tests`.

We should try the autobahn tests with `org.gradle.parallel=false` and see if anything is flaky.

A potential better idea is to take all test tasks in `autobahn-tests` and pair by pair define a `mustRunAfter` relationship to enforce sequential order:
https://gradle-community.slack.com/archives/CAHSN3LDN/p1655844616795239

The best, though, might be to declare a build service which is exactly meant for this, and concurrency can be defined there:
https://gradle-community.slack.com/archives/CAHSN3LDN/p1655853136913959?thread_ts=1655844616.795239&cid=CAHSN3LDN
