### ISSUE TITLE
Web Socket build in does'nt work well for me.

### ISSUE THREAD

**Issue by EugeneSid** [joffrey-bion/krossbow#259]
I am trying to implement STOMP client in my android project using krossbow 4.1.0 applying two ways to create connection, with custom web socket and default.
I try to init default socket and app is crashing when I calling init function same as in official tutorial:
`WebSocketClient.builtIn()`
Trying to use different version of java (latest one as well) didn't change anything same as testing app on different android versions.
Catching crash info with try/catch didn't make a job and  I still cant find an issue.
So what I am doing wrong?

**Comment by joffrey-bion** [comment]
Hi, thanks for the report.

Could you please let me know which krossbow dependencies you added to your project? Did you add the `krossbow-websocket-builtin`?

Also, it would be great if you could share which exception you're getting in the logs. Thanks a lot

**Comment by EugeneSid** [comment]
> Hi, thanks for the report.
> 
> Could you please let me know which krossbow dependencies you added to your project? Did you add the `krossbow-websocket-builtin`?
> 
> Also, it would be great if you could share which exception you're getting in the logs. Thanks a lot

My main dependencies related with krossbow is:
   ```
 implementation 'org.hildan.krossbow:krossbow-stomp-jackson:4.1.0'
 implementation 'org.hildan.krossbow:krossbow-stomp-core:4.1.0'
 implementation 'org.hildan.krossbow:krossbow-websocket-builtin:4.1.0'
 implementation 'org.hildan.krossbow:krossbow-websocket-core:4.1.0'
```

And I'll provide some log info:
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.stomptest, PID: 5064
    java.lang.NoClassDefFoundError: Failed resolution of: Ljava/net/http/HttpClient;
        at org.hildan.krossbow.websocket.jdk.Jdk11WebSocketClient.<init>(Jdk11WebSocketClient.kt:21)
        at org.hildan.krossbow.websocket.builtin.BuiltInExtensionKt.builtIn(BuiltInExtension.kt:6)
        at com.example.stomptest.MainActivity.connectStomp(MainActivity.kt:42)
        at com.example.stomptest.MainActivity.initElements$lambda-0(MainActivity.kt:64)
        at com.example.stomptest.MainActivity.$r8$lambda$NXQ2Ur_e_ehim6ZqS9_IiBx6lRI(Unknown Source:0)
        at com.example.stomptest.MainActivity$$ExternalSyntheticLambda0.onClick(Unknown Source:4)
        at android.view.View.performClick(View.java:7448)
        at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1194)
        at android.view.View.performClickInternal(View.java:7425)
        at android.view.View.access$3600(View.java:810)
        at android.view.View$PerformClick.run(View.java:28305)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "java.net.http.HttpClient" on path: DexPathList[[dex file "/data/data/com.example.stomptest/code_cache/.overlay/base.apk/classes3.dex", zip file "/data/app/~~V4gNYVQa4ro_bjEG0FVuIg==/com.example.stomptest-dBPEEAiHXcfkR5EaTLksjQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~V4gNYVQa4ro_bjEG0FVuIg==/com.example.stomptest-dBPEEAiHXcfkR5EaTLksjQ==/lib/x86, /system/lib, /system_ext/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at org.hildan.krossbow.websocket.jdk.Jdk11WebSocketClient.<init>(Jdk11WebSocketClient.kt:21) 
        at org.hildan.krossbow.websocket.builtin.BuiltInExtensionKt.builtIn(BuiltInExtension.kt:6) 
        at com.example.stomptest.MainActivity.connectStomp(MainActivity.kt:42) 
        at com.example.stomptest.MainActivity.initElements$lambda-0(MainActivity.kt:64) 
        at com.example.stomptest.MainActivity.$r8$lambda$NXQ2Ur_e_ehim6ZqS9_IiBx6lRI(Unknown Source:0) 
        at com.example.stomptest.MainActivity$$ExternalSyntheticLambda0.onClick(Unknown Source:4) 
        at android.view.View.performClick(View.java:7448) 
        at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1194) 
        at android.view.View.performClickInternal(View.java:7425) 
        at android.view.View.access$3600(View.java:810) 
        at android.view.View$PerformClick.run(View.java:28305) 
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7656) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
```

Thank you!

**Comment by joffrey-bion** [comment]
Oh I see. Thanks a lot for the additional info, and sorry for the delay. The built-in client for Java uses the JDK11 `HttpClient` which is not available on Android.

So if you're on Android I would suggest using either the OkHttp implementation or the Ktor one instead of `krossbow-websocket-builtin`.

Also, note that you shouldn't need to manually add `krossbow-websocket-core` at all, as all implementations transitively depend on it anyway.

**Comment by EugeneSid** [comment]
> Oh I see. Thanks a lot for the additional info, and sorry for the delay. The built-in client for Java uses the JDK11 `HttpClient` which is not available on Android.
> 
> So if you're on Android I would suggest using either the OkHttp implementation or the Ktor one instead of `krossbow-websocket-builtin`.
> 
> Also, note that you shouldn't need to manually add `krossbow-websocket-core` at all, as all implementations transitively depend on it anyway.

Oh ok. I'll try it and thanks a lot for your help I apreciate it!

**Comment by joffrey-bion** [comment]
Don't hesitate to open other issues if you face problems. I tried to be as clear as possible in the documentation about the supported platform, but I have to admit it's not very clear for Android. I'll try to do something about it.
