### ISSUE TITLE
[android] Failed to connect at STOMP protocol level to host

### ISSUE THREAD

**Issue by EslamMohamed3396** [joffrey-bion/krossbow#275]
**When trying to connect on android  **
My Code : 

    lifecycleScope.launch {
            val client = StompClient(OkHttpWebSocketClient())
            try {
                val session =
                    client.connect(
                        host = "/",
                        url = BuildConfig.SOCKET_STOMP,
                        customStompConnectHeaders = mapOf("Authorization" to "Bearer ${preferences.currentUser?.authToken}"),
                        sessionCoroutineContext = Dispatchers.Default
                    )
                session.use {
                        val subscription: Flow<String> =
                            it.subscribeText("${Constants.CHATS.SUBSCRIPE_CHAT}${channelId}")
                        val firstMessage: String = subscription.first()
                        //getMessage(firstMessage)
                        Log.d("ChatsViewModel", "openConnectionWithChat:${firstMessage} ")
                        val gson = Gson()
                        val json = gson.toJson(bodyText())
                        it.sendText(
                            "${Constants.CHATS.DESTINATION_CHAT}${channelId}",
                            json.toString()
                        )
                    }

            } catch (ex: Exception) {
                ex.printStackTrace()
            }
        }

The Error Is :
```
2022-10-22 18:35:56.089 10151-10151/com.docformative.docformative W/System.err: org.hildan.krossbow.stomp.StompConnectionException: Failed to connect at STOMP protocol level to host '/'
2022-10-22 18:35:56.090 10151-10151/com.docformative.docformative W/System.err:     at org.hildan.krossbow.stomp.StompWsExtensionsKt.stomp(StompWsExtensions.kt:36)
2022-10-22 18:35:56.090 10151-10151/com.docformative.docformative W/System.err:     at org.hildan.krossbow.stomp.StompWsExtensionsKt$stomp$1.invokeSuspend(Unknown Source:13)
2022-10-22 18:35:56.090 10151-10151/com.docformative.docformative W/System.err:     at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2022-10-22 18:35:56.090 10151-10151/com.docformative.docformative W/System.err:     at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
2022-10-22 18:35:56.090 10151-10151/com.docformative.docformative W/System.err:     at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
2022-10-22 18:35:56.090 10151-10151/com.docformative.docformative W/System.err:     at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
2022-10-22 18:35:56.090 10151-10151/com.docformative.docformative W/System.err:     at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:367)
2022-10-22 18:35:56.091 10151-10151/com.docformative.docformative W/System.err:     at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith$default(DispatchedContinuation.kt:278)
2022-10-22 18:35:56.091 10151-10151/com.docformative.docformative W/System.err:     at kotlinx.coroutines.internal.ScopeCoroutine.afterCompletion(Scopes.kt:28)
2022-10-22 18:35:56.091 10151-10151/com.docformative.docformative W/System.err:     at kotlinx.coroutines.JobSupport.continueCompleting(JobSupport.kt:936)
2022-10-22 18:35:56.091 10151-10151/com.docformative.docformative W/System.err:     at kotlinx.coroutines.JobSupport.access$continueCompleting(JobSupport.kt:27)
2022-10-22 18:35:56.091 10151-10151/com.docformative.docformative W/System.err:     at kotlinx.coroutines.JobSupport$ChildCompletion.invoke(JobSupport.kt:1155)
2022-10-22 18:35:56.091 10151-10151/com.docformative.docformative W/System.err:     at kotlinx.coroutines.JobSupport.notifyCompletion(JobSupport.kt:1520)
2022-10-22 18:35:56.091 10151-10151/com.docformative.docformative W/System.err:     at kotlinx.coroutines.JobSupport.completeStateFinalization(JobSupport.kt:323)
2022-10-22 18:35:56.091 10151-10151/com.docformative.docformative W/System.err:     at kotlinx.coroutines.JobSupport.finalizeFinishingState(JobSupport.kt:240)
2022-10-22 18:35:56.091 10151-10151/com.docformative.docformative W/System.err:     at kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.kt:906)
2022-10-22 18:35:56.091 10151-10151/com.docformative.docformative W/System.err:     at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:863)
2022-10-22 18:35:56.091 10151-10151/com.docformative.docformative W/System.err:     at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:828)
2022-10-22 18:35:56.092 10151-10151/com.docformative.docformative W/System.err:     at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:100)
2022-10-22 18:35:56.092 10151-10151/com.docformative.docformative W/System.err:     at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
2022-10-22 18:35:56.092 10151-10151/com.docformative.docformative W/System.err:     at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
2022-10-22 18:35:56.092 10151-10151/com.docformative.docformative W/System.err:     at android.os.Handler.handleCallback(Handler.java:938)
2022-10-22 18:35:56.092 10151-10151/com.docformative.docformative W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
2022-10-22 18:35:56.092 10151-10151/com.docformative.docformative W/System.err:     at android.os.Looper.loopOnce(Looper.java:210)
2022-10-22 18:35:56.092 10151-10151/com.docformative.docformative W/System.err:     at android.os.Looper.loop(Looper.java:299)
2022-10-22 18:35:56.092 10151-10151/com.docformative.docformative W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:8293)
2022-10-22 18:35:56.092 10151-10151/com.docformative.docformative W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2022-10-22 18:35:56.092 10151-10151/com.docformative.docformative W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
2022-10-22 18:35:56.092 10151-10151/com.docformative.docformative W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
2022-10-22 18:35:56.093 10151-10151/com.docformative.docformative W/System.err: Caused by: java.lang.IllegalStateException: Expected CONNECTED frame in response to CONNECT, got org.hildan.krossbow.stomp.frame.StompEvent$HeartBeat@b9a59a
2022-10-22 18:35:56.093 10151-10151/com.docformative.docformative W/System.err:     at org.hildan.krossbow.stomp.StompWsExtensionsKt.awaitConnectedFrame(StompWsExtensions.kt:58)
2022-10-22 18:35:56.093 10151-10151/com.docformative.docformative W/System.err:     at org.hildan.krossbow.stomp.StompWsExtensionsKt.access$awaitConnectedFrame(StompWsExtensions.kt:1)
2022-10-22 18:35:56.093 10151-10151/com.docformative.docformative W/System.err:     at org.hildan.krossbow.stomp.StompWsExtensionsKt$awaitConnectedFrame$1.invokeSuspend(Unknown Source:13)
2022-10-22 18:35:56.093 10151-10151/com.docformative.docformative W/System.err:     at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2022-10-22 18:35:56.093 10151-10151/com.docformative.docformative W/System.err: 	... 9 more
```

* krossbow-stomp-core:4.2.0 : 4.2.0
* krossbow-websocket-okhttp :4.2.0

**Comment by joffrey-bion** [comment]
Hi, thanks a lot for the report! At first glance, 2 things catch my attention:

1. the `host` is set to `/` in the `client.connect(...)` call, why is that? `/` is not a valid host, so this seems strange. Is there a specific reason you're overriding it instead of letting the default be the URL's host?
2. the connection fails on reception of a heart beat, but there should be no heartbeat received during a connection, because they are setup based on the `CONNECT`/`CONNECTED` frames pair. I wonder if something is going on with the server. Could you please share a bit of context with this? Does it happen in particular circumstances?

**Comment by EslamMohamed3396** [comment]
When i'm not setting the host, 
the host took my url and got the same error 
Failed to connect at STOMP protocol level to host : docformative.alvo.dev
when setting it with null ,
Failed to connect at STOMP protocol level to host : null
my url is : wss://docformative.alvo.dev/core/ws-pure

**Comment by EslamMohamed3396** [comment]
When remove the hos attribute : 
i get :

2022-10-23 07:32:16.142 26183-26183/com.docformative.docformative W/System.err: ### **org.hildan.krossbow.stomp.StompConnectionException: Failed to connect at STOMP protocol level to host 'docformative.alvo.dev'**
2022-10-23 07:32:16.142 26183-26183/com.docformative.docformative W/System.err:     at org.hildan.krossbow.stomp.StompWsExtensionsKt.stomp(StompWsExtensions.kt:36)
2022-10-23 07:32:16.142 26183-26183/com.docformative.docformative W/System.err:     at org.hildan.krossbow.stomp.StompWsExtensionsKt$stomp$1.invokeSuspend(Unknown Source:13)
2022-10-23 07:32:16.142 26183-26183/com.docformative.docformative W/System.err:     at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2022-10-23 07:32:16.142 26183-26183/com.docformative.docformative W/System.err:     at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
2022-10-23 07:32:16.142 26183-26183/com.docformative.docformative W/System.err:     at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
2022-10-23 07:32:16.142 26183-26183/com.docformative.docformative W/System.err:     at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
2022-10-23 07:32:16.143 26183-26183/com.docformative.docformative W/System.err:     at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:367)
2022-10-23 07:32:16.143 26183-26183/com.docformative.docformative W/System.err:     at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith$default(DispatchedContinuation.kt:278)
2022-10-23 07:32:16.143 26183-26183/com.docformative.docformative W/System.err:     at kotlinx.coroutines.internal.ScopeCoroutine.afterCompletion(Scopes.kt:28)
2022-10-23 07:32:16.143 26183-26183/com.docformative.docformative W/System.err:     at kotlinx.coroutines.JobSupport.continueCompleting(JobSupport.kt:936)
2022-10-23 07:32:16.143 26183-26183/com.docformative.docformative W/System.err:     at kotlinx.coroutines.JobSupport.access$continueCompleting(JobSupport.kt:27)
2022-10-23 07:32:16.143 26183-26183/com.docformative.docformative W/System.err:     at kotlinx.coroutines.JobSupport$ChildCompletion.invoke(JobSupport.kt:1155)
2022-10-23 07:32:16.143 26183-26183/com.docformative.docformative W/System.err:     at kotlinx.coroutines.JobSupport.notifyCompletion(JobSupport.kt:1520)
2022-10-23 07:32:16.143 26183-26183/com.docformative.docformative W/System.err:     at kotlinx.coroutines.JobSupport.completeStateFinalization(JobSupport.kt:323)
2022-10-23 07:32:16.143 26183-26183/com.docformative.docformative W/System.err:     at kotlinx.coroutines.JobSupport.finalizeFinishingState(JobSupport.kt:240)
2022-10-23 07:32:16.143 26183-26183/com.docformative.docformative W/System.err:     at kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.kt:906)
2022-10-23 07:32:16.143 26183-26183/com.docformative.docformative W/System.err:     at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:863)
2022-10-23 07:32:16.143 26183-26183/com.docformative.docformative W/System.err:     at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:828)
2022-10-23 07:32:16.144 26183-26183/com.docformative.docformative W/System.err:     at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:100)
2022-10-23 07:32:16.144 26183-26183/com.docformative.docformative W/System.err:     at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
2022-10-23 07:32:16.144 26183-26183/com.docformative.docformative W/System.err:     at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
2022-10-23 07:32:16.144 26183-26183/com.docformative.docformative W/System.err:     at android.os.Handler.handleCallback(Handler.java:938)
2022-10-23 07:32:16.144 26183-26183/com.docformative.docformative W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
2022-10-23 07:32:16.144 26183-26183/com.docformative.docformative W/System.err:     at android.os.Looper.loopOnce(Looper.java:210)
2022-10-23 07:32:16.144 26183-26183/com.docformative.docformative W/System.err:     at android.os.Looper.loop(Looper.java:299)
2022-10-23 07:32:16.144 26183-26183/com.docformative.docformative W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:8293)
2022-10-23 07:32:16.144 26183-26183/com.docformative.docformative W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2022-10-23 07:32:16.144 26183-26183/com.docformative.docformative W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
2022-10-23 07:32:16.145 26183-26183/com.docformative.docformative W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
2022-10-23 07:32:16.145 26183-26183/com.docformative.docformative **### W/System.err: Caused by: org.hildan.krossbow.stomp.StompErrorFrameReceived: Bad CONNECT**
2022-10-23 07:32:16.145 26183-26183/com.docformative.docformative W/System.err:     at org.hildan.krossbow.stomp.StompSocket.decodeStomp(StompSocket.kt:45)
2022-10-23 07:32:16.145 26183-26183/com.docformative.docformative W/System.err:     at org.hildan.krossbow.stomp.StompSocket.access$decodeStomp(StompSocket.kt:14)
2022-10-23 07:32:16.145 26183-26183/com.docformative.docformative W/System.err:     at org.hildan.krossbow.stomp.StompSocket$special$$inlined$map$1$2.emit(Emitters.kt:224)
2022-10-23 07:32:16.145 26183-26183/com.docformative.docformative W/System.err:     at kotlinx.coroutines.flow.FlowKt__ErrorsKt$catchImpl$2.emit(Errors.kt:158)
2022-10-23 07:32:16.145 26183-26183/com.docformative.docformative W/System.err:     at kotlinx.coroutines.flow.FlowKt__ChannelsKt.emitAllImpl$FlowKt__ChannelsKt(Channels.kt:62)
2022-10-23 07:32:16.145 26183-26183/com.docformative.docformative W/System.err:     at kotlinx.coroutines.flow.FlowKt__ChannelsKt.access$emitAllImpl$FlowKt__ChannelsKt(Channels.kt:1)
2022-10-23 07:32:16.145 26183-26183/com.docformative.docformative W/System.err:     at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(Unknown Source:14)
2022-10-23 07:32:16.145 26183-26183/com.docformative.docformative W/System.err:     at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2022-10-23 07:32:16.145 26183-26183/com.docformative.docformative W/System.err: 	... 9 more

**Comment by joffrey-bion** [comment]
Thanks for the extra information. I'll make the connection resistant to weird heart beats, but it might not fix your root issue.

Maybe the initial connection/session is not closed (despite the `use` maybe your coroutine is not cancelled and thus the session not closed). The could explain why some heartbeat is received during the next handshake.

By the way, do you control the server? Do you any suspicious logs there?

**Comment by EslamMohamed3396** [comment]
i'm using lifecycleScope for coroutine , this scope will be cancelled when the Lifecycle is destroyed. when close the fragment, the lifecycle destroyed, 
i will try to close the coroutine manually,
 sorry i don't have any control on the server
> Thanks for the extra information. I'll make the connection resistant to weird heart beats, but it might not fix your root issue.
> 
> Maybe the initial connection/session is not closed (despite the `use` maybe your coroutine is not cancelled and thus the session not closed). The could explain why some heartbeat is received during the next handshake.
> 
> By the way, do you control the server? Do you see any suspicious logs there?

**Comment by joffrey-bion** [comment]
Yep I'm aware of how `lifecycleScope` behaves, but since cancellation is cooperative, there is no real guarantee that the coroutine will be completed and the session closed. Technically we know it will be cancelled but it might still be cleaning up stuff (on non-cancellable blocks). That's also just a wild assumption of course, maybe logging after the `use` could help identify if that's the case.

In any case I'll make the handshake more lenient in this respect, maybe under a config option. I'm just trying to assess if you have a deeper problem, and whether this weird heartbeat is just a symptom

**Comment by EslamMohamed3396** [comment]
> Yep I'm aware of how `lifecycleScope` behaves, but since cancellation is cooperative, there is no real guarantee that the coroutine will be completed and the session closed. Technically we know it will be cancelled but it might still be cleaning up stuff (on non-cancellable blocks). That's also just a wild assumption of course, maybe logging after the `use` could help identify if that's the case.
> 
> In any case I'll make the handshake more lenient in this respect, maybe under a config option. I'm just trying to assess if you have a deeper problem, and whether this weird heartbeat is just a symptom


I will try now to force cancel and ping you

**Comment by joffrey-bion** [comment]
@EslamMohamed3396 did you get the chance to understand how you're getting heartbeats there from a previous connection?

I was thinking that even if I add a feature/config to ignore such heartbeats during the handshake, if those heartbeats continue afterwards they might not match the expectations of a potential new heartbeat negotiation result (from the new connection). So depending on why you get them, it's likely still going to be a problem.

**Comment by EslamMohamed3396** [comment]
> 

sorry for my late reply, i'm still get this error, i don't know why really, i'm getting it when make connection for second time, i should wait for 20 - 60 second, to make successful connection

**Comment by joffrey-bion** [comment]
@EslamMohamed3396 thanks for getting back to me. Is the server you're accessing public? I wish I could manage to reproduce this locally

**Comment by EslamMohamed3396** [comment]
> @EslamMohamed3396 thanks for getting back to me. Is the server you're accessing public? I wish I could manage to reproduce this locally

@joffrey-bion 
i can give you the url and authorization

**Comment by joffrey-bion** [comment]
Wow, that would be great, you can reach me at [joffrey.bion@gmail.com](mailto:joffrey.bion@gmail.com)

**Comment by joffrey-bion** [comment]
@EslamMohamed3396 did you send anything to me? I haven't received anything, but I may have missed it.

**Comment by EslamMohamed3396** [comment]
> @EslamMohamed3396 did you send anything to me? I haven't received anything, but I may have missed it.
@joffrey-bion 
sorry, but the backend developer make something in a server to monitor this issue, i think he will resolve it from his side, i will ping you with news

**Comment by joffrey-bion** [comment]
Oh, ok. Perfect then! Yes, please let me know the result of the investigation

**Comment by joffrey-bion** [comment]
@EslamMohamed3396 did you have any news on this?

**Comment by EslamMohamed3396** [comment]
@joffrey-bion  the backend team didn't get back to me, you can close this issue and when i have a result could i open it again ? if there is any problem ?

**Comment by joffrey-bion** [comment]
No problem, I was just wondering whether there was any progress or not :)

**Comment by EslamMohamed3396** [comment]
@joffrey-bion  Hello,
My backend team fixed the issue, thanks for your support <3

**Comment by joffrey-bion** [comment]
Good to hear, any insight on what the problem was?
