### ISSUE TITLE
WebSocket was closed while subscriptions were still active

### ISSUE THREAD

**Issue by Shusek** [joffrey-bion/krossbow#397]
### What happened?

Recently, I integrated WebSocket lifecycle monitoring into our production mobile application. While monitoring, I've noticed that we frequently encounter the error message: "WebSocket was closed while subscriptions were still active." However, I am uncertain about the root cause of this issue. While the message is quite clear, I don't understand why such an exception is raised. If the websocket is closed, it is quite clear that the subscribers should also be closed.

In my WebSocket usecase, the connection remains active for whole the duration of live application, and if any issues occur within the stream, it should automatically reconnect and report what happened. Unfortunately, I cannot repeat this error locally and I have no idea what causes it. It's possible that I'm using the library incorrectly. 

Code showing roughly how it works
```
   reconnectEventFlow.onStart { emit(Unit) }
            .flatMapLatest { _ ->
                callbackFlow {
                    val errorHandler = CoroutineExceptionHandler { _, exception ->
                        close(exception)
                    }
                    val sessionCoroutineContext = EmptyCoroutineContext + errorHandler
                    val connection: StompSessionWithKxSerialization =
                        stompSessionConnection.connectSession(sessionCoroutineContext).also {
                            send(it)
                        }
                    awaitSuspendClose { connection.safeDisconnect() }
                }.flatMapLatest { subscribeChannels(it) }
            }
            .retryWhen { _, _ ->
                true
            }  .shareIn(MainScope(), SharingStarted.WhileSubscribed())

```

StackTrace:
`Non-fatal Exception: org.hildan.krossbow.stomp.WebSocketClosedUnexpectedly: the WebSocket was closed while subscriptions were still active. Code: 1013 Reason: 
       at org.hildan.krossbow.stomp.StompSocketKt.decodeToStompEvent(StompSocket.kt:89)
       at org.hildan.krossbow.stomp.StompSocketKt.access$decodeToStompEvent(StompSocket.kt:1)
       at org.hildan.krossbow.stomp.StompSocket.decodeStomp(StompSocket.kt:39)
       at org.hildan.krossbow.stomp.StompSocket.access$decodeStomp(StompSocket.kt:14)
       at org.hildan.krossbow.stomp.StompSocket$special$$inlined$map$1$2.emit(StompSocket.kt:224)
       at kotlinx.coroutines.flow.FlowKt__ErrorsKt$catchImpl$2.emit(Errors.kt:158)
       at kotlinx.coroutines.flow.FlowKt__ErrorsKt$catchImpl$2.emit(Errors.kt:158)
       at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:15)
       at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:15)
       at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:87)
       at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:66)
       at org.hildan.krossbow.websocket.ktor.KtorWebSocketConnectionAdapter$incomingFrames$2.invokeSuspend(KtorWebSocketConnectionAdapter.java:56)
       at org.hildan.krossbow.websocket.ktor.KtorWebSocketConnectionAdapter$incomingFrames$2.invoke(KtorWebSocketConnectionAdapter.java:62)
       at org.hildan.krossbow.websocket.ktor.KtorWebSocketConnectionAdapter$incomingFrames$2.invoke(KtorWebSocketConnectionAdapter.java:282)
       at kotlinx.coroutines.flow.FlowKt__EmittersKt$onCompletion$$inlined$unsafeFlow$1.collect(SafeCollector.common.kt:128)
       at kotlinx.coroutines.flow.FlowKt__EmittersKt$onCompletion$$inlined$unsafeFlow$1$1.invokeSuspend(SafeCollector.common.kt:1)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.java:584)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)`

### Krossbow version

5.8.0

### Krossbow modules

krossbow-stomp-core, krossbow-stomp-kxserialization, krossbow-stomp-kxserialization-json, krossbow-websocket-core, krossbow-websocket-ktor, krossbow-websocket-okhttp

### Kotlin version

1.9.10

### Kotlin target platforms

Android

**Comment by joffrey-bion** [comment]
Thanks a lot for the detailed report. I will review that exception more closely, because the message is based on the assumption that receiving a web socket level Close frame only happens if the WS was closed "unexpectedly" (without disconnecting the STOMP session as a whole). I need to check this assumption again, and maybe adjust how the exception is thrown.

**Comment by Shusek** [comment]
I was able to repeat this locally when the websocket undergoes maintenance but instead throw 500 on endpoint " wss://mywebsocket" return 101 as if everything was working but I'm not sure that the same thing happened to users on production.

**Comment by joffrey-bion** [comment]
Thanks for the additional info, this is quite useful. Yeah that is what the exception is supposed to cover. Basically the connection being unexpectedly closed without disconnection at the STOMP level. So most likely this is a server failure that is reported as an exception to subscription collectors, which is good. I'd still like to make sure there aren't other cases that could trigger this error

**Comment by joffrey-bion** [comment]
A new case: https://github.com/joffrey-bion/krossbow/discussions/561

**Comment by joffrey-bion** [comment]
Do you face the issue sporadically? Or do you have a specific situation that you know consistently reproduces the problem?

Sorry that this issue didn't really move forward so far.

**Comment by IbrahimEzzatSaad** [comment]
@joffrey-bion  I think the issue is in that code, it decodes the frames to send it back in a flow to the subscriber, thinking it would be handled from there

```
private fun WebSocketFrame.decodeToStompEvent(): StompEvent {
    if (isHeartBeat()) {
        return StompEvent.HeartBeat
    }
    return when (this) {
        is WebSocketFrame.Text -> text.decodeToStompFrame()
        is WebSocketFrame.Binary -> bytes.decodeToStompFrame()
        is WebSocketFrame.Ping,
        is WebSocketFrame.Pong
        -> StompEvent.HeartBeat // we need to count this traffic
        is WebSocketFrame.Close -> throw WebSocketClosedUnexpectedly(code, reason)
    }
}
```

The reason why it send this exception that onClose sending WebSocketFrame.Close
```
  /**
     * Sends a [WebSocketFrame.Close] to the [incomingFrames] flow, and completes it normally.
     *
     * This adapter cannot be used anymore after a call to this method; calling any method may throw an exception.
     */
    fun onClose(code: Int, reason: String?): ChannelResult<Unit> {
        val result = frames.trySend(WebSocketFrame.Close(code, reason))
        frames.close()
        return result
    }
```

If we took the exception message as well, which says that Websocket was closed while sbscriptions were still active, maybe we should have unsubscribed first before closing the websocket?

```
  override suspend fun disconnect() {
        if (config.gracefulDisconnect) {
            sendDisconnectFrameAndWaitForReceipt()
        }

        stompSocket.close()
        sharedStompEvents.emit(StompEvent.Close)

    }
```

That the disconnect function and there a function for unsubscribing but its not being called in disconnect

```
   private suspend fun unsubscribe(subscriptionId: String) {
        sendRawStompFrame(StompFrame.Unsubscribe(StompUnsubscribeHeaders(id = subscriptionId)))
    }
```

**Comment by IbrahimEzzatSaad** [comment]
@joffrey-bion Yeah, I'm only disconnecting, and it crashes with the error: "WebSocket was closed while subscriptions were still active."

I made a small change that seems to fix it, and I can open a PR if you’d like.

In the BaseStompSession file, I modified the disconnect function to unsubscribe from all active subscriptions before disconnecting. This way, the subscribers don’t receive the disconnect frame—meaning they’ll only get it if it actually comes from the server side.

```
 override suspend fun disconnect() {
        subscribers.forEach {
            unsubscribe(it)
        }
        delay(5000)
        if (config.gracefulDisconnect) {
            sendDisconnectFrameAndWaitForReceipt()
        }

        stompSocket.close()
        sharedStompEvents.emit(StompEvent.Close)
        subscribers.clear()
    }
```
