### ISSUE TITLE
No transformation found: ByteBufferChannel to DefaultClientWebSocketSession

### ISSUE THREAD

**Issue by NikkyAI** [joffrey-bion/krossbow#88]
**Describe the bug**

A clear and concise description of what the bug is, including what happens and what you expected.

**Reproduction and additional details**

first attemtp to se STOMP to connect to a spring-boot server

```
import kotlinx.coroutines.flow.*
import org.hildan.krossbow.stomp.*
import kotlinx.coroutines.*
import kotlinx.serialization.ExperimentalSerializationApi
import org.hildan.krossbow.stomp.conversions.kxserialization.withJsonConversions
import org.hildan.krossbow.websocket.ktor.KtorWebSocketClient
import kotlin.jvm.JvmStatic

public object StompTest {
    @OptIn(ExperimentalSerializationApi::class)
    @JvmStatic
    public fun main(args: Array<String>): Unit = runBlocking {
        val url = "ws://localhost:8080/ws-endpoint"
        val client = StompClient(
            webSocketClient = KtorWebSocketClient()
        ) // custom WebSocketClient and other config can be passed in here
        val session = client.connect(url) // optional login/passcode can be provided here

        session.use {
            session.sendText("/app/hello", """{"name": "test"}""")

// this triggers a SUBSCRIBE frame and returns the flow of messages for the subscription
            val subscription: Flow<String> = session.subscribeText("/topic/greetings")

            val collectorJob = launch {
                subscription.collect { msg ->
                    println("Received: $msg")
                }
            }
            delay(3000)
// cancelling the flow collector triggers an UNSUBSCRIBE frame
            collectorJob.cancel()
        }

    }
}
```

```
Exception in thread "main" org.hildan.krossbow.stomp.WebSocketConnectionException: Failed to connect at web socket level to ws://localhost:8080/ws-endpoint
	at org.hildan.krossbow.stomp.StompClient.webSocketConnect(StompClient.kt:74)
	at org.hildan.krossbow.stomp.StompClient$webSocketConnect$1.invokeSuspend(StompClient.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:188)
...
    at com.tryformation.api.StompTest.main(StompTest.kt:14)
Caused by: io.ktor.client.call.NoTransformationFoundException: No transformation found: class io.ktor.utils.io.ByteBufferChannel (Kotlin reflection is not available) -> class io.ktor.client.features.websocket.DefaultClientWebSocketSession (Kotlin reflection is not available)
with response from ws://localhost:8080/ws-endpoint:
status: 200 
response headers: 
Vary: Origin
, Vary: Access-Control-Request-Method
, Vary: Access-Control-Request-Headers
, Content-Type: text/plain;charset=UTF-8
, Content-Length: 19
, Date: Wed, 06 Jan 2021 22:26:30 GMT
```

i tried adding `kotlin("reflect")` but that seemed to have changed nothing

**Context**

Kotlin version: 1.4.21
Krossbow version: 1.1.2
Kotlin target: jvm
Artifacts used:
- [x] `krossbow-stomp-core`
- [ ] `krossbow-stomp-jackson`
- [ ] `krossbow-stomp-kxserialization`
- [x] `krossbow-websocket-core`
- [ ] `krossbow-websocket-sockjs`
- [ ] `krossbow-websocket-spring`
- [ ] `krossbow-websocket-okhttp`

If you can, please provide a bit of context about what you were trying to achieve (it helps to have use cases in mind when fixing the problem or adding new features).

**Comment by joffrey-bion** [comment]
Hi, thanks for opening this issue. I will look into this ASAP, as I've never encountered this error before.

**Comment by NikkyAI** [comment]
full stacktrace

```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" org.hildan.krossbow.stomp.WebSocketConnectionException: Failed to connect at web socket level to ws://localhost:8080/ws-endpoint
	at org.hildan.krossbow.stomp.StompClient.webSocketConnect(StompClient.kt:74)
	at org.hildan.krossbow.stomp.StompClient$webSocketConnect$1.invokeSuspend(StompClient.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:188)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:144)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:90)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:188)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:144)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:90)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:188)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:144)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:90)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:188)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:144)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:90)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:188)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:144)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:90)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:84)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at com.tryformation.api.StompTest.main(StompTest.kt:14)
Caused by: io.ktor.client.call.NoTransformationFoundException: No transformation found: class io.ktor.utils.io.ByteBufferChannel (Kotlin reflection is not available) -> class io.ktor.client.features.websocket.DefaultClientWebSocketSession (Kotlin reflection is not available)
with response from ws://localhost:8080/ws-endpoint:
status: 200 
response headers: 
Vary: Origin
, Vary: Access-Control-Request-Method
, Vary: Access-Control-Request-Headers
, Content-Type: text/plain;charset=UTF-8
, Content-Length: 19
, Date: Wed, 06 Jan 2021 23:11:29 GMT

	at io.ktor.client.call.HttpClientCall.receive(HttpClientCall.kt:86)
	at io.ktor.client.features.websocket.BuildersKt.webSocketSession(builders.kt:180)
	at io.ktor.client.features.websocket.BuildersKt$webSocketSession$1.invokeSuspend(builders.kt)
	... 34 more
```

wit the default client (running on openjdk 14)
```
Exception in thread "main" org.hildan.krossbow.stomp.WebSocketConnectionException: Failed to connect at web socket level to ws://localhost:8080/ws-endpoint
	at org.hildan.krossbow.stomp.StompClient.webSocketConnect(StompClient.kt:74)
	at org.hildan.krossbow.stomp.StompClient$webSocketConnect$1.invokeSuspend(StompClient.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:84)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at com.tryformation.api.StompTest.main(StompTest.kt:14)
Caused by: org.hildan.krossbow.websocket.WebSocketConnectionException: Couldn't connect to web socket at ws://localhost:8080/ws-endpoint
	at org.hildan.krossbow.websocket.jdk.Jdk11WebSocketClient.connect(Jdk11WebSocketClient.kt:37)
	at org.hildan.krossbow.websocket.jdk.Jdk11WebSocketClient$connect$1.invokeSuspend(Jdk11WebSocketClient.kt)
	... 9 more
Caused by: java.net.http.WebSocketHandshakeException
	at java.net.http/jdk.internal.net.http.websocket.OpeningHandshake.resultFrom(OpeningHandshake.java:224)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1146)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:840)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: jdk.internal.net.http.websocket.CheckFailedException: Unexpected HTTP response status code 200
	at java.net.http/jdk.internal.net.http.websocket.OpeningHandshake.checkFailed(OpeningHandshake.java:334)
	at java.net.http/jdk.internal.net.http.websocket.OpeningHandshake.handleResponse(OpeningHandshake.java:243)
	at java.net.http/jdk.internal.net.http.websocket.OpeningHandshake.resultFrom(OpeningHandshake.java:220)
	... 10 more
```

i am thinking i am not configuring this correctly to match up with the serverside on spring

**Comment by joffrey-bion** [comment]
Thanks a lot for the additional info.

The issue with the Ktor client is likely a bug in Krossbow, as the module is quite recent (not even in jcenter yet) and I haven't tested it so far (I'm currently working on web socket client tests). I will look into this.

But I'm really surprised about the error you get on the default JDK client.
Maybe you're using SockJS on server side?

**Comment by joffrey-bion** [comment]
I can confirm that this is caused by using Ktor client on a SockJS server. Ktor client works fine otherwise.

If you're using Spring Boot, either remove `.withSockJS()` from your STOMP configuration or switch to `krossbow-websocket-sockjs` for your websocket client.
